### ISSUE TITLE
Unable to flip joystick axis in config

### ISSUE THREAD

**Issue by ghost** [RetroPie/pifba#14]
Editing /opt/retropie/emulators/pifba/fba2x.cfg:
JA_UD_1=0 gives me the correct joystick axis, but it is inverted. 
JA_UD_1=-0 does not flip the axis.

Any chance of fixing this?
Thanks

**Comment by joolswills** [comment]
Unfortunately not - we don't develop this emulator - but there may be a better emulator alternative for oyu. Please use the RetroPie forum for help and provide details of your set-up. Have not heard of this problem before. Joystick wired incorrectly?
